M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu23.04.1} date So 23 Jul 2023 13:36:54
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-23T13:36:54+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu23.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X120.38Y-54.38
X126.16Y-54.38
T0
M30
